### ISSUE TITLE
Project Setup and Basic Infrastructure

### ISSUE THREAD

**Issue by codemaxy** [codemaxy/tab-state-manager#1]
# Initial Project Setup and Development Environment

## Objective
Set up the foundational development environment for tab-state-manager package

## Tasks
- [x] Initialize project using TSDX
```bash
npx tsdx create tab-state-manager
cd tab-state-manager
```
- [x]  Configure TypeScript
- Add strict mode
- Set target to ES6
- Configure module resolution

- [x] Set up testing environment
- Configure Jest
- Add React Testing Library

- [x] Configure Storybook

```bash
npx sb init
```
- [x]  Set up GitHub Actions for CI/CD
- Add workflow for tests
- Add workflow for build
- Add workflow for npm publish

- [x] Configure package.json
- Add proper metadata
- Configure build scripts
- Set up peer dependencies

### Acceptance Criteria
- Repository initialized with TSDX
- TypeScript properly configured
- Testing environment ready
- Storybook running
- CI/CD pipelines set up
- `package.json` properly configured

**Comment by SujalXplores** [comment]
@codemaxy I would like to contribute to this issue.

**Comment by codemaxy** [comment]
@SujalXplores Please go ahead! Happy coding
